# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci(provider: "travis")
    increment_build_number(xcodeproj: "Runner.xcodeproj")
    match(type: "appstore")
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
  end
end

platform :ios do
  desc "Resign development"
  lane :dev do
    setup_ci(provider: "travis")
    match(type: "development")
    resign(
        ipa: ENV['IPA_FILE'],
        signing_identity: ENV['IOS_DEVELOPMENT_SIGNING_IDENTITY'],
        provisioning_profile: ENV['sigh_com.whysh.community_development_profile-path']
     )
  end
end